//
//  painting.swift
//  Artector
//
//  Created by Lujain Yhia on 11/06/1445 AH.
//


import Foundation
struct Painting: Identifiable {
    var id = UUID()
    var name: String
    var artist: String
    var artistStory: String
    var paintingStory: String
    var paintingDescription: String
    
}

let paintings = [
    "thestarrynight": Painting(name: "Starry Night", artist: "Vincent van Gogh", artistStory: "Vincent van Gogh was a Dutch Post-Impressionist painter whose work had a profound impact on the art world despite his relatively short and tumultuous life. Vincent Willem van Gogh was born in Zundert, Netherlands, to a middle-class family. He showed an early interest in art but initially pursued a career in various professions, including working as an art dealer, teacher, and preacher. incent van Gogh died on July 29, 1890, at the age of 37, from a gunshot wound, likely self-inflicted. The circumstances surrounding his death remain the subject of debate, with some suggesting it was suicide and others considering the possibility of accidental injury.", paintingStory: "The Starry Night is one of Vincent van Gogh's most famous and iconic paintings. Painted in June 1889, it is considered a masterpiece of Post-Impressionist art. Vincent van Gogh painted The Starry Night while he was a patient at the Saint-Paul-de-Mausole asylum in Saint-Rémy-de-Provence, France. He created the work from memory and imagination rather than directly observing the night sky.During his time in Saint-Rémy, Van Gogh experienced periods of emotional turbulence and struggled with mental health issues. It is believed that the swirling, dynamic composition of The Starry Night reflects his inner emotional state.", paintingDescription: "The painting features a night sky dominated by swirling, turbulent patterns of stars. The sky occupies the upper two-thirds of the canvas, creating a cosmic and expansive feeling.The landscape below includes a cypress tree on the left side, a steepled village with red-roofed buildings, and a mountainous backdrop.Van Gogh employed a rich and vibrant color palette, with bold and intense hues. The sky is dominated by deep blues and purples, while the stars are depicted in bright, swirling yellows.The village and landscape below are rendered in darker tones, creating a contrast with the radiant night sky.The stars in the night sky are a central motif of the painting. They are depicted with swirling, circular motions, creating a dynamic and mesmerizing effect.The stars seem to pulsate with energy, conveying a sense of cosmic movement and vitality.Van Gogh's characteristic impasto technique is evident in the thick and textured application of paint. The swirling patterns in the sky and the expressive brushstrokes contribute to the sense of movement and emotion.The impasto technique adds a tactile quality to the painting, inviting viewers to engage with the surface."),
    
    
    "monalisa": Painting(name: "Mona Lisa", artist: "Leonardo da Vinci", artistStory: "The artist history: Leonardo da Vinci was a polymath of the Italian Renaissance, excelling in various fields such as painting, sculpture, anatomy, engineering, mathematics, and architecture. His life story is rich and multifaceted,eonardo was born in Vinci, Italy, as the illegitimate son of Ser Piero da Vinci, a notary, and Caterina, a peasant woman. He spent his early years in Vinci and later moved to Florence.Leonardo da Vinci passed away on May 2, 1519, at the age of 67, at Clos Lucé. The exact cause of his death is uncertain, but it is believed to be related to a stroke.", paintingStory: "the Mona Lisa story : The exact reason why Leonardo da Vinci painted the Mona Lisa is not definitively known, and the subject has been a source of speculation and debate among art historians. Leonardo da Vinci began working on the painting around 1503, and it is believed to have been commissioned by a wealthy Florentine merchant named Francesco del Giocondo, whose wife, Lisa Gherardini, is thought to be the subject of the portrait.", paintingDescription: "painting description : The painting depicts a woman, widely believed to be Lisa Gherardini, the wife of Florentine merchant Francesco del Giocondo,The subject is shown sitting against a distant landscape with a winding river and a bridge.She is positioned in a three-quarter view, with her body turned slightly and her gaze fixed on the viewer,One of the most captivating aspects of the painting is the subject's enigmatic smile, which has been a subject of much discussion and interpretation,The woman is dressed in a modest, dark-colored gown, and she wears a veil or headscarf.Her clothing is characteristic of the fashion of the time, reflecting the early 16th century.The background of the painting features a landscape with a winding river, distant mountains, and a bridge.The landscape creates a sense of depth and adds to the overall atmosphere of the painting."),
    
    
    "theraftofthemedusa": Painting(name: "The Raft of the Medusa", artist: "Théodore Géricault", artistStory: "The artist history :Théodore Géricault was a French Romantic painter known for his dramatic and emotionally charged works.Théodore Géricault was born on September 26, 1791, in Rouen, France, into a wealthy and socially prominent family.Géricault's personal life was marked by financial difficulties and health issues. He was known for his intense and passionate personality, which sometimes led to conflicts with others.", paintingStory: "The Raft of the Medusa story : is a monumental painting created by the French Romantic artist Théodore Géricault in 1819. The painting depicts a tragic event from French naval history, known as the wreck of the frigate Méduse in 1816. Théodore Géricault painted The Raft of the Medusa as a response to a tragic and controversial event in French naval history—the wreck of the frigate Méduse in 1816. There are several reasons why Géricault chose to depict this specific event in his artwork:éricault was deeply moved by the human suffering and tragedy that unfolded during the shipwreck. The survivors endured extreme conditions, including hunger, thirst, exposure, and even resorting to cannibalism. Géricault felt a sense of empathy and compassion for the victims, and he sought to bring attention to their plight.", paintingDescription: "painting description :The color palette is dominated by earthy tones, with a focus on browns, grays, and muted colors, creating a somber and desolate atmosphere.The use of muted colors contributes to the realism of the scene, emphasizing the harshness of the survivors' plight.Géricault paid careful attention to capturing the psychological and emotional states of the figures. Faces show a range of emotions, including anguish, desperation, and resignation.The expressions on the faces of the figures contribute to the overall emotional impact of the painting, eliciting empathy from the viewer."),
    
    
    "womenofalgiers": Painting(name: "Women Of Algiers ", artist: "Eugène Delacroix ", artistStory: "The artist history : Eugène Delacroix was a French Romantic artist whose works had a profound impact on the 19th-century art scene. Delacroix's interest in art was evident from a young age. He received his early artistic training under the painter Pierre-Narcisse Guérin.In 1815, he entered the École des Beaux-Arts in Paris, where he studied with other influential artists of the time.Eugène Delacroix passed away on August 13, 1863, in Paris, at the age of 65. His death marked the end of an era in French painting.", paintingStory: "women of algiers story : The Women of Algiers refers to a famous series of 15 paintings created by the French Romantic artist Eugène Delacroix. These paintings were inspired by Delacroix's visit to North Africa, particularly Algiers (now part of Algeria), in 1832. The most renowned painting from this series is Women of Algiers in Their Apartment.Delacroix's journey to North Africa was a significant source of inspiration for him. His fascination with the exoticism, colors, and culture of Algiers is evident in this series.", paintingDescription: "painting description : The painting features a harem-like setting, portraying an intimate scene within the private quarters of Algerian women.The composition is intricate and dynamic, with several women engaged in various activities. Delacroix carefully arranged the figures to create a harmonious yet vibrant tableau.The central focus is on a reclining woman in the foreground, adorned with sumptuous fabrics and jewelry. Her pose exudes a sense of languor and sensuality.Other women are depicted around her, engaged in activities such as playing musical instruments, reading, and conversing. Each figure is dressed in luxurious garments, contributing to the overall opulence of the scene.Delacroix employed a rich and vibrant color palette, characterized by intense reds, blues, and golds. The colors contribute to the exotic and luxurious atmosphere of the painting.The patterns on the textiles, the tiles on the floor, and the details of the women's clothing showcase Delacroix's meticulous attention to color and design.The interior of the apartment is adorned with intricate decorations, textiles, and objects. Delacroix used these details to enhance the overall richness and exoticism of the scene.The architectural elements, including the archways and windows, add depth and perspective to the composition."),
    
    
    "theweddingatcana": Painting(name: "The Wedding at Cana", artist: "Paolo Veronese", artistStory: "The artist history : Paolo Veronese, born Paolo Caliari, was an Italian Renaissance painter renowned for his grand and opulent compositions, vivid colors, and masterful use of perspective. Paolo began his artistic training under the local artist Antonio Badile. He also studied the works of other Renaissance masters such as Titian and Giorgione.Paolo Veronese passed away on April 19, 1588, in Venice, at the age of 60. He was buried in the church of San Sebastiano.", paintingStory: "The Wedding at Can story : The story of The Wedding at Cana is a biblical narrative found in the Gospel of John, specifically in John 2:1-11. The account describes a wedding feast in the town of Cana in Galilee, where Jesus performed his first public miracle. Jesus and his disciples, along with his mother Mary, were invited to a wedding feast in the town of Cana. During the celebration, the hosts ran out of wine. In the cultural context of the time, running out of wine during a wedding feast was a significant and embarrassing issue. Mary, the mother of Jesus, was aware of the situation and approached her son. She simply told him, They have no more wine.Initially, Jesus responded somewhat cryptically to his mother, saying, Woman, what does this have to do with me? My hour has not yet come. Some interpretations suggest that Jesus was indicating that his public ministry and the manifestation of his divine power were not to be initiated at that moment.", paintingDescription: "painting description : The painting is large in scale, measuring about 6.77 meters by 9.94 meters.The composition is grand and opulent, reflecting the festive nature of the wedding celebration.The scene is filled with a multitude of figures engaged in dynamic and theatrical activities.The central focus is on Jesus, Mary, and the young couple getting married. They are positioned prominently within the composition.Mary, wearing a blue robe, is gesturing toward Jesus, directing attention to him.Jesus is shown at the moment of performing the miracle, with a servant pouring water into a large container.Veronese employed a rich and vibrant color palette, with a harmonious interplay of colors.The clothing of the figures is adorned with luxurious fabrics, and the overall ambiance is one of opulence and celebration. The painting is rich in details, including intricate patterns on the clothing, elaborate architectural elements, and various objects that contribute to the sense of festivity. The facial expressions of the figures convey a range of emotions, from joyous celebration to curiosity.")
]
